//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileSurveillanceWebApplication.Models.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.FriendShips = new HashSet<FriendShip>();
            this.FriendShips1 = new HashSet<FriendShip>();
            this.Trajectories = new HashSet<Trajectory>();
        }
    
        public long Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Fullname { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public bool IsActive { get; set; }
        public string Avatar { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Address { get; set; }
        public bool Gender { get; set; }
        public int RoleId { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual ICollection<FriendShip> FriendShips { get; set; }
        public virtual ICollection<FriendShip> FriendShips1 { get; set; }
        public virtual ICollection<Trajectory> Trajectories { get; set; }
    }
}
