//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileSurveillanceWebApplication.Models.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapturedImage
    {
        public long Id { get; set; }
        public string ImageUrl { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public bool IsActive { get; set; }
        public string LocationId { get; set; }
    
        public virtual Location Location { get; set; }
    }
}
