//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileSurveillanceWebApplication.Models.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationRoute
    {
        public string StartLocationId { get; set; }
        public string DestinationLocationId { get; set; }
        public string TravelMode { get; set; }
        public string RouteString { get; set; }
        public string TrajectoryId { get; set; }
    }
}
